@startuml usecase_diagram_ridotto
left to right direction
skinparam packageStyle rectangle
skinparam usecase {
    BackgroundColor LightCyan
    BorderColor DarkCyan
    ArrowColor DarkCyan
}
skinparam actor {
    BackgroundColor Khaki
    BorderColor DarkGoldenRod
}

actor "Cliente" as C
actor "Game Master\n(Operatore)" as GM
actor "Admin" as A

rectangle "EscapeManager System" {
    
    usecase "Fruire del Catalogo\ne Prenotare Esperienze" as UC_Macro1
    usecase "Gestione Operativa\ndella Filiale" as UC_Macro2
    usecase "Amministrazione Centrale\ne Politiche Commerciali" as UC_Macro3

}

C --> UC_Macro1
GM --> UC_Macro2
A --> UC_Macro3

@enduml